sudo: required

language: ruby
rvm:
  - 2.2

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - bundle exec rake test

addons:
  code_climate:
    repo_token: 683ec4c66a12e8212b328523e894dd74064f340847357fb208b5bc5a9fb7e31e